version: '3'
services:
  movies:
    image: vemula7777/repomovies:latest
    ports:
      - "80:80"
    deploy:
      replicas: 3

  train:
    image: vemula7777/repotrain:latest
    ports:
      - "81:80"
    deploy:
      replicas: 3

  dth:
    image: vemula7777/repodth:latest
    ports:
      - "82:80"
    deploy:
      replicas: 3

  recharge:
    image: vemula7777/reporecharge:latest
    ports:
      - "93:80"
    deploy:
      replicas: 3
